### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by recantha** [zspitzer/lucee-performance-analyzer#1]
![perfanalyzer_issue](https://user-images.githubusercontent.com/2105614/78332297-af443280-757f-11ea-9e25-cb1b83f6afc5.jpg)
I'm getting an error (see the image) after first installing the plugin and then clicking on the Performance link below Plugins in the menu.

invalid component definition, can't find component [lucee_plugin_directory.PerformanceAnalyzer.Action]

The Error Occurred in
/admin/plugin.cfm: line 14
called from /admin/web.cfm: line 466
called from /admin/server.cfm: line 2

**Comment by recantha** [comment]
This only happens when I install it in the Server side of admin. In Web it comes up. Is that intentional?

**Comment by zspitzer** [comment]
alas this is a known Lucee issue https://luceeserver.atlassian.net/browse/LDEV-2785

it works after restarting Lucee

I have another PR to fix all these loading issues and share extensions between server and web admins, you can't access a plugin installed at the server level in the web admin 

https://github.com/lucee/Lucee/pull/901
https://luceeserver.atlassian.net/browse/LDEV-2791
